'use client';
import {useEffect,useState} from 'react';
import {useAuth} from '../../../context/AuthContext';
import {getAnalytics,type AnalyticsData} from '../../../services/admin/analytics.service';
import {AnalyticsTable} from './AnalyticsTable';
import {TrafficSources} from './TrafficSources';
import {ApiError} from '../../../services/api-client';
export default function Analytics(){
 const {accessToken}=useAuth();const [days,setDays]=useState('30'),[revision,setRevision]=useState(0);const key=JSON.stringify([accessToken,days,revision]);
 const [result,setResult]=useState<{key:string;data?:AnalyticsData;error?:string}>();
 useEffect(()=>{if(!accessToken)return;let active=true;getAnalytics(days,accessToken).then(data=>{if(active)setResult({key,data});}).catch(error=>{if(active)setResult({key,error:error instanceof ApiError?error.message:'Unable to load Google Analytics.'});});return()=>{active=false;};},[key,days,accessToken]);
 const current=result?.key===key?result:undefined,data=current?.data;
 const values=data?.configured?data.reports.overview.rows[0]?.values??[]:[];
 return <div className="p-admin-margin-mobile md:p-admin-margin-desktop space-y-8"><header className="flex flex-wrap justify-between items-end gap-6"><div><h1 className="font-serif text-4xl">Storefront Analytics</h1><p className="mt-3 text-admin-on-surface-variant">Audience and shopping activity from Google Analytics 4.</p></div><div className="flex gap-3"><label className="sr-only" htmlFor="analytics-period">Report period</label><select id="analytics-period" value={days} onChange={e=>setDays(e.target.value)} className="border bg-transparent px-4 py-3 text-sm">{['7','30','90'].map(day=><option key={day} value={day}>Last {day} days</option>)}</select><button onClick={()=>setRevision(n=>n+1)} className="border px-4 py-3 text-xs uppercase">Refresh</button></div></header>
 {!current?<div role="status" className="space-y-5 animate-pulse"><span className="sr-only">Loading analytics</span>{[0,1,2].map(i=><div key={i} className="h-28 bg-admin-surface-container-high"/>)}</div>:current.error?<div role="alert" className="border p-6"><p>{current.error}</p><button onClick={()=>setRevision(n=>n+1)} className="mt-4 underline">Retry</button></div>:data&&!data.configured?<div className="border border-admin-outline-variant bg-white p-8"><h2 className="font-serif text-2xl">Connect Google Analytics</h2><p className="mt-4 text-sm">Enable GA4_ENABLED and configure GA4_PROPERTY_ID and GA4_SERVICE_ACCOUNT_JSON_BASE64 on the backend. The service account needs Viewer access to your GA4 property.</p><p className="mt-3 text-sm">Storefront tracking also requires NEXT_PUBLIC_GA_ENABLED and NEXT_PUBLIC_GA_MEASUREMENT_ID in the frontend. See docs/google-analytics.md for setup.</p></div>:data?.configured&&<>
 <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{['Active users','Sessions','Page views','Engagement rate'].map((label,index)=><div key={label} className="border border-admin-outline-variant bg-white p-6"><h2 className="text-xs uppercase tracking-widest">{label}</h2><p className="mt-4 font-serif text-3xl">{index===3?((values[index]??0)*100).toFixed(1)+'%':(values[index]??0).toLocaleString()}</p></div>)}</div>
 <p className="text-xs text-admin-on-surface-variant">Fetched {new Date(data.fetchedAt).toLocaleString('en-CA')}. Cached for 5 minutes. Includes today in the GA property time zone; reports are not real-time. Consent, blockers and Google processing affect coverage. Database sales reports remain the source of truth.</p>
 <section className="border border-admin-outline-variant bg-white p-6"><h2 className="font-serif text-2xl mb-4">Daily sessions</h2>{data.reports.daily.rows.length?<div className="overflow-x-auto"><div className="flex items-end gap-2 h-44 min-w-max">{data.reports.daily.rows.map(row=><div key={row.label} className="flex flex-col justify-end items-center h-full w-9" title={`${row.label}: ${row.values[0]} sessions`}><span className="text-[9px]">{row.values[0]}</span><div className="w-5 bg-admin-primary" style={{height:`${(row.values[0]??0)/Math.max(1,...data.reports.daily.rows.map(r=>r.values[0]??0))*120}px`}}/><span className="text-[9px] mt-2">{row.label.slice(4,6)}/{row.label.slice(6,8)}</span></div>)}</div></div>:<p className="text-sm">No sessions recorded.</p>}</section>
 <div className="grid xl:grid-cols-2 gap-6"><AnalyticsTable title="Traffic channels" report={data.reports.channels} columns={['Sessions']}/>{data.reports.sources?<AnalyticsTable title="Source / Medium" report={{...data.reports.sources,rows:data.reports.sources.rows.slice(0,10)}} columns={['Sessions','Active users']}/>:<section className="border border-admin-outline-variant bg-white p-6"><h2 className="font-serif text-2xl mb-4">Source / Medium</h2><p className="text-sm">Deploy the updated backend to enable this report.</p></section>}<AnalyticsTable title="Popular pages" report={data.reports.pages} columns={['Views']}/><AnalyticsTable title="Countries" report={data.reports.countries} columns={['Active users']}/><AnalyticsTable title="Devices" report={data.reports.devices} columns={['Sessions']}/><AnalyticsTable title="Shopping events (event counts)" report={data.reports.events} columns={['Events']}/><AnalyticsTable title="Products (top by views)" report={data.reports.products} columns={['Viewed','Added units','Purchased units']}/></div>
 <p className="text-xs text-admin-on-surface-variant">Top tables show up to 10 rows. Shopping event counts are not a user conversion funnel. Purchase events require the customer to reach the confirmed success page with analytics consent.</p>
 <TrafficSources report={data.reports.sources}/>
 </>}</div>;
}
