'use client';
import {useEffect,useState} from 'react';
import {useAuth} from '../../../context/AuthContext';
import {inventoryService,filterInventory,stockLabel,type InventoryItem} from '../../../services/admin/inventory.service';
import {InventorySummary} from './InventorySummary';
import {InventoryAdjustmentModal} from './InventoryAdjustmentModal';
export default function Inventory(){
 const {accessToken}=useAuth();const [revision,setRevision]=useState(0),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<InventoryItem>(),[message,setMessage]=useState('');
 const key=JSON.stringify([accessToken,revision]);const [result,setResult]=useState<{key:string;items?:InventoryItem[];error?:string}>();
 useEffect(()=>{if(!accessToken)return;let active=true;inventoryService.list(accessToken).then(items=>{if(active)setResult({key,items});}).catch(()=>{if(active)setResult({key,error:'Unable to load inventory. Please try again.'});});return()=>{active=false;};},[accessToken,key]);
 const current=result?.key===key?result:undefined;const items=current?.items??[],filtered=filterInventory(items,search,status),pages=Math.max(1,Math.ceil(filtered.length/20)),currentPage=Math.min(page,pages);
 const refresh=()=>setRevision(n=>n+1);
 return <div className="p-admin-margin-mobile md:p-admin-margin-desktop"><header className="flex flex-wrap justify-between items-end gap-6"><div><h1 className="font-serif text-4xl">Inventory</h1><p className="mt-3 text-admin-on-surface-variant">Stock levels and reservation-aware adjustments for your provisions.</p></div><button onClick={refresh} className="border px-4 py-3 text-xs uppercase">Refresh</button></header>
 {message&&<p role="status" className="mt-6 border border-neutral-700 text-neutral-800 p-4">{message}</p>}
 {!current?<div role="status" className="space-y-4 mt-8 animate-pulse"><span className="sr-only">Loading inventory</span>{[0,1,2,3,4].map(i=><div key={i} className="h-20 bg-admin-surface-container-high rounded-sm"/>)}</div>:current.error?<p role="alert" className="mt-8">{current.error} <button onClick={refresh} className="underline">Retry</button></p>:<><InventorySummary items={items}/><p className="text-xs text-admin-on-surface-variant mb-6">Summary covers all inventory records. Available = on hand − reserved. Low stock means 1–10 available units.</p><div className="grid sm:grid-cols-2 gap-4 mb-6"><label className="text-xs uppercase tracking-widest">Search<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Product, variant or SKU" className="block w-full border border-admin-outline-variant bg-transparent p-3 mt-2"/></label><label className="text-xs uppercase tracking-widest">Stock status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}} className="block w-full border border-admin-outline-variant bg-transparent p-3 mt-2"><option value="">All stock</option>{['In stock','Low stock','Out of stock'].map(label=><option key={label}>{label}</option>)}</select></label></div>
 <div className="overflow-x-auto border border-admin-outline-variant"><table className="w-full text-left text-sm"><thead className="bg-admin-surface-container-low"><tr>{['Product / variant','SKU','On hand','Reserved','Available','Status','Action'].map(label=><th key={label} className="p-4 font-medium whitespace-nowrap">{label}</th>)}</tr></thead><tbody>{filtered.slice((currentPage-1)*20,currentPage*20).map(item=><tr key={item.variantId} className="border-t border-admin-outline-variant"><td className="p-4 min-w-48"><p className="font-serif text-lg">{item.product}</p><p className="text-xs text-admin-on-surface-variant">{item.name||'Standard'}</p></td><td className="p-4 text-xs break-all">{item.sku}</td><td className="p-4">{item.quantity}</td><td className="p-4">{item.reservedQuantity}</td><td className="p-4 font-semibold">{item.availableQuantity}</td><td className="p-4 whitespace-nowrap text-xs">{stockLabel(item.availableQuantity)}</td><td className="p-4"><button onClick={()=>{setSelected(item);setMessage('');}} className="bg-admin-primary text-white px-4 py-2 text-xs">Adjust</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center">No inventory records match your filters.</p>}</div>
 <nav aria-label="Inventory pagination" className="flex justify-between items-center gap-4 mt-6 text-sm"><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)} className="border px-4 py-2 disabled:opacity-40">Previous</button><span>{filtered.length} variants · {currentPage} / {pages}</span><button disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)} className="border px-4 py-2 disabled:opacity-40">Next</button></nav></>}
 {selected&&accessToken&&<InventoryAdjustmentModal item={selected} token={accessToken} onClose={()=>setSelected(undefined)} onRefresh={refresh} onSaved={()=>{setSelected(undefined);setMessage('Inventory adjusted successfully.');refresh();}}/>}</div>;
}
