'use client';
import {useRef,useState,type FormEvent} from 'react';
import {Modal} from '../../ui/Modal';
import {inventoryAdjustmentSchema,type InventoryItem,type InventoryAdjustment} from '../../../services/admin/inventory.service';
import {adjustInventory} from '../../../services/admin/inventory.actions';
import {ApiError} from '../../../services/api-client';
export function InventoryAdjustmentModal({item,token,onClose,onSaved,onRefresh}:{item:InventoryItem;token:string;onClose:()=>void;onSaved:()=>void;onRefresh:()=>void}){
 const [direction,setDirection]=useState('add'),[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false),[confirmation,setConfirmation]=useState<InventoryAdjustment>();const sending=useRef(false);
 function review(event:FormEvent){event.preventDefault();setError('');const units=Number(quantity);if(!quantity.trim()||units<=0){setError('Enter a positive whole number of units.');return;}const parsed=inventoryAdjustmentSchema.safeParse({change:direction==='add'?units:-units,reason});if(!parsed.success){setError(parsed.error.issues[0].message);return;}if(item.quantity+parsed.data.change<item.reservedQuantity){setError('You cannot remove stock reserved for existing orders.');return;}setConfirmation(parsed.data);}
 async function save(){if(!confirmation||sending.current||locked)return;sending.current=true;setBusy(true);setError('');try{await adjustInventory(item.variantId,confirmation,token);onSaved();}catch(cause){setError(cause instanceof ApiError?cause.message:'Unable to confirm the adjustment. Refresh inventory before trying again.');setLocked(true);onRefresh();}finally{setBusy(false);sending.current=false;}}
 return <Modal open onClose={()=>{if(!sending.current)onClose();}} title="Adjust inventory"><h2 className="font-serif text-2xl pr-8">Adjust inventory</h2><p className="mt-3 text-sm">{item.product} · {item.name||'Standard'}</p><p className="mt-1 text-xs break-all text-[#7A7264]">{item.sku}</p><p className="text-xs mt-4">On hand: {item.quantity} · Reserved: {item.reservedQuantity} · Available: {item.availableQuantity}</p>
 {error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}
 {locked?<button onClick={onClose} className="underline mt-6 text-sm">Close and check refreshed inventory</button>:confirmation?<div className="mt-6 space-y-4"><p className="text-sm">Confirm {confirmation.change>0?'adding':'removing'} {Math.abs(confirmation.change)} units.</p><p className="text-sm">Expected on hand: <strong>{item.quantity+confirmation.change}</strong><br/>Expected available: <strong>{item.availableQuantity+confirmation.change}</strong></p><p className="text-sm whitespace-pre-wrap break-words">Reason: {confirmation.reason}</p><p className="text-xs text-[#7A7264]">Stock may change while you work. The server checks reservations and applies this adjustment to the latest quantity.</p><div className="flex gap-3"><button disabled={busy} onClick={save} className="bg-[#1C1A17] text-white px-5 py-3 text-xs">{busy?'Saving...':'Confirm adjustment'}</button><button disabled={busy} onClick={()=>setConfirmation(undefined)} className="border px-5 py-3 text-xs">Back</button></div></div>:<form onSubmit={review} className="mt-6 space-y-4"><label className="block text-sm">Adjustment<select value={direction} onChange={e=>setDirection(e.target.value)} className="block w-full border border-[#E1D9CA] rounded-lg bg-transparent p-3 mt-2"><option value="add">Add stock</option><option value="remove">Remove stock</option></select></label><label className="block text-sm">Units<input required type="number" min="1" max="1000000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} className="block w-full border border-[#E1D9CA] rounded-lg p-3 mt-2"/></label><label className="block text-sm">Reason<textarea required maxLength={500} rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="e.g. New stock received or damaged items" className="block w-full border border-[#E1D9CA] rounded-lg p-3 mt-2"/></label><button className="bg-[#1C1A17] text-white px-5 py-3 text-xs">Review adjustment</button></form>}</Modal>;
}
