import React from 'react';
import { ArrowRight, ChefHat, Clock, Sparkles } from 'lucide-react';
import { getRecipes, type Recipe } from '../services/recipes.service';
import { RecipeCardSkeleton } from '../components/ui/RecipeCardSkeleton';
import { RecipeDetailModal } from '../components/RecipeDetailModal';

export const RecipesView: React.FC = () => {
  const [recipes, setRecipes] = React.useState<Recipe[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [page, setPage] = React.useState(1);
  const [totalPages, setTotalPages] = React.useState(1);
  const [selected, setSelected] = React.useState<Recipe | null>(null);
  React.useEffect(() => { let cancelled = false; setLoading(true); getRecipes(page, 6).then((result) => { if (!cancelled) { setRecipes(result.items); setTotalPages(result.pagination.totalPages); } }).catch(() => { if (!cancelled) setRecipes([]); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [page]);
  return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-16 space-y-12">
    <header className="space-y-4 max-w-3xl"><div className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-[#D4AF37]"><Sparkles className="w-3.5 h-3.5" /> Recipes & Gastronomy</div><h1 className="font-serif text-3xl sm:text-5xl font-normal text-[#1C1A17]">The Kitchen Journals</h1><p className="text-xs sm:text-sm text-[#6B6457] leading-relaxed">Nigerian recipes documented with clear methods, essential equipment, and practical notes for confident cooking at home.</p></header>
    <section className="space-y-8"><div className="flex items-center justify-between pb-3 border-b border-[#E8E2D5]"><h2 className="font-serif text-2xl font-bold text-[#1C1A17] flex items-center gap-2"><ChefHat className="w-5 h-5 text-[#D4AF37]" /> Featured recipes</h2><span className="text-xs text-[#8C8475] font-semibold uppercase tracking-wider">{recipes.length} recipes</span></div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{loading ? Array.from({ length: 3 }, (_, i) => <RecipeCardSkeleton key={i} />) : recipes.length ? recipes.map((recipe) => <article key={recipe.id} className="bg-[#FAF9F5] border border-[#E8E2D5] rounded-sm overflow-hidden flex flex-col group hover:shadow-lg transition-all"><button type="button" onClick={() => setSelected(recipe)} className="relative h-64 bg-[#EFECE4] overflow-hidden text-left"><img src={recipe.image || '/product-placeholder.svg'} alt={recipe.title} referrerPolicy="no-referrer" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" /><span className="absolute top-3 left-3 bg-[#1C1A17]/90 text-[#FAF9F5] text-[10px] uppercase font-bold tracking-widest px-2.5 py-1">{recipe.procedures.length} steps</span></button><div className="p-6 flex flex-1 flex-col justify-between space-y-5"><div className="space-y-2"><h3 className="font-serif text-xl font-bold text-[#1C1A17]">{recipe.title}</h3><p className="text-xs text-[#7A7264] line-clamp-3 leading-relaxed">{recipe.notes || 'A carefully documented Nigerian kitchen recipe.'}</p></div><div className="pt-4 border-t border-[#EAE4D7] flex items-center justify-between text-xs font-semibold"><span className="flex items-center gap-1 text-[#8C8475]"><Clock className="w-3.5 h-3.5" /> {recipe.procedures.length} steps</span><button type="button" onClick={() => setSelected(recipe)} className="flex items-center gap-1">Read Recipe <ArrowRight className="w-3.5 h-3.5 text-[#D4AF37]" /></button></div></div></article>) : <p className="md:col-span-3 text-sm text-[#7A7264]">Recipes coming soon.</p>}</div>
      {!loading && totalPages > 1 && <div className="flex items-center justify-center gap-3 pt-4"><button type="button" disabled={page === 1} onClick={() => setPage((current) => current - 1)} className="border border-[#D9D2C5] px-4 py-2 text-xs font-bold uppercase tracking-wider text-[#1C1A17] disabled:opacity-40 disabled:cursor-not-allowed">Previous</button><span className="text-xs font-semibold text-[#6B6457]">Page {page} of {totalPages}</span><button type="button" disabled={page >= totalPages} onClick={() => setPage((current) => current + 1)} className="bg-[#1C1A17] px-4 py-2 text-xs font-bold uppercase tracking-wider text-[#FAF9F5] disabled:opacity-40 disabled:cursor-not-allowed">Next</button></div>}
    </section><RecipeDetailModal recipe={selected} onClose={() => setSelected(null)} />
  </div>;
};
