'use client';
import {useRef,useState,type FormEvent} from 'react';
import {categoryInputSchema,categorySlug,type Category} from '../../../services/admin/categories.service';
import {createCategory} from '../../../services/admin/categories.actions';
import {ApiError} from '../../../services/api-client';
export function CategoryForm({token,onCreated}:{token:string;onCreated:(category:Category)=>void}){
 const [name,setName]=useState(''),[slug,setSlug]=useState(''),[customSlug,setCustomSlug]=useState(false),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const sending=useRef(false);
 async function submit(event:FormEvent){event.preventDefault();if(sending.current)return;setError('');const parsed=categoryInputSchema.safeParse({name,slug,description:description.trim()||null});if(!parsed.success){setError(parsed.error.issues.map(issue=>issue.message).join(' '));return;}sending.current=true;setBusy(true);try{const created=await createCategory(parsed.data,token);setName('');setSlug('');setCustomSlug(false);setDescription('');onCreated(created);}catch(cause){setError(cause instanceof ApiError&&cause.status===409?'That category slug is already in use. Choose another slug.':cause instanceof Error?cause.message:'Unable to create category.');}finally{sending.current=false;setBusy(false);}}
 const inputClass='block w-full mt-2 border border-admin-outline-variant bg-transparent p-3 text-sm normal-case tracking-normal';
 return <form onSubmit={submit} className="border border-admin-outline-variant bg-white p-6 md:p-8 space-y-5"><h2 className="font-serif text-2xl">Add category</h2><fieldset disabled={busy} className="space-y-5 disabled:opacity-60"><label className="block text-xs uppercase tracking-widest">Name<input required maxLength={100} value={name} onChange={event=>{setName(event.target.value);if(!customSlug)setSlug(categorySlug(event.target.value));}} className={inputClass} placeholder="e.g. Grains & flour"/></label><label className="block text-xs uppercase tracking-widest">Slug<input required maxLength={100} value={slug} onChange={event=>{setCustomSlug(true);setSlug(event.target.value);}} className={inputClass} placeholder="grains-flour"/></label><p className="text-xs text-admin-on-surface-variant">Generated from the name. You can edit it; each category needs a unique slug.</p><label className="block text-xs uppercase tracking-widest">Description (optional)<textarea maxLength={1000} rows={4} value={description} onChange={event=>setDescription(event.target.value)} className={inputClass}/></label></fieldset>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="bg-admin-primary text-white px-5 py-3 text-xs uppercase tracking-widest disabled:opacity-50">{busy?'Creating…':'Create category'}</button></form>;
}
