'use client';
import {useEffect,useState} from 'react';
import {useAuth} from '../../../context/AuthContext';
import {categoriesService,type Category} from '../../../services/admin/categories.service';
import {CategoryForm} from './CategoryForm';
export default function Categories(){
 const {accessToken}=useAuth();const [revision,setRevision]=useState(0),[search,setSearch]=useState(''),[message,setMessage]=useState('');const key=JSON.stringify([accessToken,revision]);
 const [result,setResult]=useState<{key:string;rows?:Category[];error?:string}>();
 useEffect(()=>{if(!accessToken)return;let active=true;categoriesService.list().then(rows=>{if(active)setResult({key,rows});}).catch(error=>{if(active)setResult({key,error:error instanceof Error?error.message:'Unable to load categories.'});});return()=>{active=false;};},[key,accessToken]);
 const current=result?.key===key?result:undefined,rows=current?.rows??[],filtered=rows.filter(row=>[row.name,row.slug].join(' ').toLowerCase().includes(search.trim().toLowerCase()));
 return <div className="p-admin-margin-mobile md:p-admin-margin-desktop space-y-8"><header><p className="text-xs uppercase tracking-widest text-admin-on-surface-variant">Catalog organization</p><h1 className="font-serif text-4xl mt-3">Categories</h1><p className="mt-3 text-admin-on-surface-variant">Create categories for your products and storefront filters.</p></header>{message&&<p role="status" className="border border-admin-outline-variant p-4 text-sm">{message}</p>}<div className="grid xl:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)] gap-8 items-start"><section className="space-y-5"><div className="flex flex-wrap gap-3 items-end"><label className="flex-1 text-xs uppercase tracking-widest">Search categories<input type="search" value={search} onChange={e=>setSearch(e.target.value)} className="block w-full mt-2 border border-admin-outline-variant bg-transparent p-3 text-sm"/></label><button onClick={()=>setRevision(n=>n+1)} className="border border-admin-outline-variant px-4 py-3 text-xs uppercase">Refresh</button></div>{!current?<div role="status" className="space-y-3 animate-pulse"><span className="sr-only">Loading categories</span>{[0,1,2].map(i=><div key={i} className="h-24 bg-admin-surface-container-high"/>)}</div>:current.error?<p role="alert">{current.error} <button className="underline" onClick={()=>setRevision(n=>n+1)}>Retry</button></p>:<><p className="text-xs text-admin-on-surface-variant">{filtered.length} categories</p>{!filtered.length?<p className="border border-admin-outline-variant p-8 text-sm">{rows.length?'No matching categories.':'No categories yet. Create your first category.'}</p>:<ul className="space-y-3">{filtered.map(category=><li key={category.id} className="border border-admin-outline-variant bg-white p-5"><div className="flex justify-between gap-4"><h2 className="font-serif text-xl">{category.name}</h2><span className="text-xs whitespace-nowrap text-admin-on-surface-variant">{category._count?.products??0} products</span></div><p className="mt-2 text-xs text-admin-on-surface-variant break-all">{category.slug}</p>{category.description&&<p className="mt-3 text-sm whitespace-pre-wrap break-words">{category.description}</p>}</li>)}</ul>}</>}</section>{accessToken&&<CategoryForm token={accessToken} onCreated={category=>{setMessage(`${category.name} created. You can now select it when adding or editing products.`);setRevision(n=>n+1);}}/>}</div></div>;
}
