import type {AdminProduct} from '../../../schemas/admin-product.schema';
import {formatCAD} from '../../../services/currency';
import {AdminImage} from '../AdminImage';
export function ProductReadOnlyDetails({product}:{product:AdminProduct}){
 return <div className="space-y-6">
 <section className="border border-admin-outline-variant bg-white p-6"><h2 className="font-serif text-xl mb-4">Product imagery</h2><p className="text-xs text-admin-on-surface-variant mb-4">Read-only. Image management is not connected yet.</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{product.images.length?product.images.map(image=><AdminImage key={image.id} src={image.url} alt={image.alt||product.name} className="w-full aspect-square object-cover"/>):<p className="text-sm">No images uploaded.</p>}</div></section>
 <section className="border border-admin-outline-variant bg-white p-6"><h2 className="font-serif text-xl mb-4">Variants & inventory</h2><p className="text-xs text-admin-on-surface-variant mb-4">Read-only. Available stock excludes reservations. Variant and inventory editing will use their own operations.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Variant / SKU','Price (CAD)','On hand','Reserved','Available','Shipping dimensions'].map(label=><th key={label} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{product.variants.map(variant=><tr key={variant.id} className="border-t"><td className="p-3">{variant.name||'Standard'}<span className="block text-xs">{variant.sku}</span></td><td className="p-3 whitespace-nowrap">{formatCAD(variant.price)}</td><td className="p-3">{variant.inventory?.quantity??0}</td><td className="p-3">{variant.inventory?.reservedQuantity??0}</td><td className="p-3">{Math.max(0,(variant.inventory?.quantity??0)-(variant.inventory?.reservedQuantity??0))}</td><td className="p-3 whitespace-nowrap">{variant.weightGrams??'—'} g<br/>{variant.lengthCm??'—'} × {variant.widthCm??'—'} × {variant.heightCm??'—'} cm</td></tr>)}</tbody></table>{!product.variants.length&&<p className="py-4">No variants added.</p>}</div></section>
 </div>;
}
