import {type AdminOrderDetail,statusLabel} from '../../../services/admin/orders.service';
import {AdminImage} from '../AdminImage';
import {orderMoney} from './OrderRow';
export function OrderDetailContent({order}:{order:AdminOrderDetail}){
 const address=order.address,profile=order.user.profile;
 return <div className="mt-6 space-y-6 text-sm"><div className="flex flex-wrap justify-between gap-3 border-b pb-4"><span className="uppercase tracking-widest text-xs">{statusLabel(order.status)}</span><span>{new Date(order.createdAt).toLocaleString('en-CA')}</span></div>
 <div className="grid sm:grid-cols-2 gap-6"><section><h3 className="font-serif text-xl mb-2">Customer</h3><p>{profile?[profile.firstName,profile.lastName].join(' '):'Customer'}</p><p className="break-all">{order.user.email}</p>{profile?.phone&&<p>{profile.phone}</p>}</section><section><h3 className="font-serif text-xl mb-2">Shipping destination</h3>{address?<><p>{address.line1}</p>{address.line2&&<p>{address.line2}</p>}<p>{[address.city,address.state,address.postalCode].filter(Boolean).join(', ')}</p><p>{address.country}</p><p className="text-xs mt-2">Current saved address; historical address snapshots are not available.</p></>:<p>Address is no longer available.</p>}<p className="mt-2">{[order.shippingCarrier,order.shippingService].filter(Boolean).join(' — ')||'No shipping service recorded'}</p></section></div>
 <section><h3 className="font-serif text-xl mb-3">Items</h3>{order.items.map(item=><div key={item.id} className="flex gap-4 py-4 border-b"><AdminImage src={item.variant?.product.images[0]?.url??''} alt={item.name} className="w-16 h-16 object-cover rounded-sm"/><div className="flex-1 min-w-0"><p>{item.name}</p><p className="text-xs break-all">SKU: {item.sku}</p><p className="text-xs mt-1">{item.quantity} × {orderMoney(item.unitPrice,order.currency)}</p></div><p>{orderMoney(item.unitPrice*item.quantity,order.currency)}</p></div>)}</section>
 <dl className="space-y-2"><div className="flex justify-between"><dt>Subtotal</dt><dd>{orderMoney(order.subtotal,order.currency)}</dd></div><div className="flex justify-between"><dt>Shipping</dt><dd>{orderMoney(order.shippingAmount,order.currency)}</dd></div><div className="flex justify-between font-semibold border-t pt-3"><dt>Total</dt><dd>{orderMoney(order.total,order.currency)}</dd></div></dl>
 <section><h3 className="font-serif text-xl mb-3">Payments</h3>{order.payments.length?order.payments.map(payment=><div key={payment.id} className="border-b py-3"><p>{payment.provider} · {statusLabel(payment.status)} · {orderMoney(payment.amount,payment.currency)}</p><p className="text-xs break-all mt-1">{payment.transactionReference}</p></div>):<p>No payment attempts recorded.</p>}</section>
 <section><h3 className="font-serif text-xl mb-3">Timeline</h3><ol className="space-y-3">{order.histories.map(history=><li key={history.id} className="border-l-2 pl-3"><p>{statusLabel(history.newStatus)}</p><time className="text-xs" dateTime={history.createdAt}>{new Date(history.createdAt).toLocaleString('en-CA')}</time></li>)}</ol>{!order.histories.length&&<p>No status changes recorded.</p>}</section></div>;
}
