import {Modal} from '../../ui/Modal';
import type {Transaction} from '../../../services/admin/transactions.service';
import {statusLabel} from '../../../services/admin/orders.service';
import {orderMoney} from '../orders/OrderRow';
import {TransactionActivity} from './TransactionActivity';
export function TransactionDetails({transaction:t,token,onClose}:{transaction:Transaction;token:string;onClose:()=>void}){
 return <Modal open onClose={onClose} title="Transaction details" maxWidth="max-w-3xl"><h2 className="font-serif text-3xl pr-8">Transaction details</h2><p className="text-xs break-all mt-3">{t.transactionReference}</p><div className="my-6 border-y border-[#E4E4E4] py-5 flex flex-wrap justify-between gap-4"><p className="font-serif text-2xl">{orderMoney(t.amount,t.currency)}</p><p className="text-sm">{statusLabel(t.status)}</p></div><dl className="grid sm:grid-cols-2 gap-4 text-sm">{[['Customer',t.order.user.email],['Order ID',t.orderId],['Order status',statusLabel(t.order.status)],['Provider',t.provider],['Created',new Date(t.createdAt).toLocaleString('en-CA')],['Payment intent',t.paymentIntentId||'Not recorded'],['Checkout session',t.checkoutSessionId||'Not recorded']].map(([label,value])=><div key={label}><dt className="text-xs text-[#535353]">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>)}</dl>{t.failureMessage&&<p className="text-sm text-neutral-700 mt-4 break-words">{t.failureMessage}</p>}
 <section className="mt-6"><h3 className="font-serif text-xl mb-3">Payment attempts</h3>{t.attempts.length?<div className="space-y-3">{[...t.attempts].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(attempt=><div key={attempt.id} className="border-b border-[#E4E4E4] pb-3 text-sm"><p>{statusLabel(attempt.status)} · {new Date(attempt.createdAt).toLocaleString('en-CA')}</p>{attempt.failureMessage&&<p className="mt-1 text-xs text-neutral-700">{attempt.failureMessage}</p>}</div>)}</div>:<p className="text-sm">No payment attempts recorded.</p>}</section><TransactionActivity id={t.id} token={token}/><p className="mt-6 text-xs text-[#535353]">Read-only payment records. No refunds, payment retries or webhook replays are triggered here.</p></Modal>;
}
