'use client';
import {useEffect,useState} from 'react';
import {useAuth} from '../../../context/AuthContext';
import {transactionsService,paymentStatuses,type Transaction} from '../../../services/admin/transactions.service';
import {statusLabel} from '../../../services/admin/orders.service';
import {orderMoney} from '../orders/OrderRow';
import {TransactionDetails} from './TransactionDetails';
import {OrderProducts} from '../orders/OrderProducts';
export default function Transactions(){
 const {accessToken}=useAuth();const [q,setQ]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[selected,setSelected]=useState<string>();
 const query=q.trim(),key=JSON.stringify([query,accessToken,revision]);const [result,setResult]=useState<{key:string;items?:Transaction[];error?:string}>();
 useEffect(()=>{if(!accessToken)return;let active=true;const timer=setTimeout(()=>{transactionsService.list(query,accessToken).then(items=>{if(active)setResult({key,items});}).catch(()=>{if(active)setResult({key,error:'Unable to load transactions. Please retry.'});});},250);return()=>{active=false;clearTimeout(timer);};},[key,query,accessToken]);
 const current=result?.key===key?result:undefined,items=current?.items??[],filtered=items.filter(item=>!status||item.status===status),pages=Math.max(1,Math.ceil(filtered.length/20)),currentPage=Math.min(page,pages),transaction=items.find(item=>item.id===selected);
 return <div className="p-admin-margin-mobile md:p-admin-margin-desktop"><header className="flex flex-wrap justify-between items-end gap-6"><div><h1 className="font-serif text-4xl">Transactions</h1><p className="mt-3 text-admin-on-surface-variant">Payment records, attempts and processing history.</p></div><button onClick={()=>setRevision(n=>n+1)} className="border px-4 py-3 text-xs uppercase">Refresh</button></header><div className="grid sm:grid-cols-2 gap-5 my-8"><label className="text-xs uppercase tracking-widest">Search<input type="search" value={q} maxLength={200} onChange={e=>{setQ(e.target.value);setPage(1);}} placeholder="Transaction reference, order ID or Stripe ID" className="block w-full mt-2 border border-admin-outline-variant bg-transparent p-3 text-sm"/></label><label className="text-xs uppercase tracking-widest">Payment status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}} className="block w-full mt-2 border border-admin-outline-variant bg-transparent p-3 text-sm"><option value="">All statuses</option>{paymentStatuses.map(value=><option key={value} value={value}>{statusLabel(value)}</option>)}</select></label></div>
 {!current?<div role="status" className="space-y-4 animate-pulse"><span className="sr-only">Loading transactions</span>{[0,1,2,3,4].map(i=><div key={i} className="h-20 bg-admin-surface-container-high"/>)}</div>:current.error?<p role="alert">{current.error} <button onClick={()=>setRevision(n=>n+1)} className="underline">Retry</button></p>:<><div className="overflow-x-auto border border-admin-outline-variant"><table className="w-full text-sm text-left"><thead className="bg-admin-surface-container-low"><tr>{['Reference / order','Customer','Amount','Payment status','Created','Details'].map(label=><th key={label} className="p-4 font-medium whitespace-nowrap">{label}</th>)}</tr></thead><tbody>{filtered.slice((currentPage-1)*20,currentPage*20).map(item=><tr key={item.id} className="border-t border-admin-outline-variant"><td className="p-4 min-w-52 break-all"><p>{item.transactionReference}</p><p className="text-xs text-admin-on-surface-variant mt-1">{item.orderId}</p><OrderProducts items={item.order.items}/></td><td className="p-4 break-all">{item.order.user.email}</td><td className="p-4 whitespace-nowrap">{orderMoney(item.amount,item.currency)}</td><td className="p-4 text-xs whitespace-nowrap">{statusLabel(item.status)}</td><td className="p-4 whitespace-nowrap">{new Date(item.createdAt).toLocaleDateString('en-CA')}</td><td className="p-4"><button onClick={()=>setSelected(item.id)} className="bg-admin-primary text-white text-xs px-4 py-2">View</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center">No transactions match your filters.</p>}</div><nav aria-label="Transaction pagination" className="mt-6 flex flex-wrap justify-between items-center gap-4 text-sm"><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)} className="border px-4 py-2 disabled:opacity-40">Previous</button><span>{filtered.length} transactions · Page {currentPage} of {pages}</span><button disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)} className="border px-4 py-2 disabled:opacity-40">Next</button></nav><p className="text-xs text-admin-on-surface-variant mt-6">Amounts use each transaction’s recorded currency. Payment status is separate from order fulfillment status.</p></>}
 {transaction&&accessToken&&<TransactionDetails transaction={transaction} token={accessToken} onClose={()=>setSelected(undefined)}/>}</div>;
}
