'use client';
import {useEffect,useState} from 'react';
import {transactionsService,type TransactionLog,type TransactionEvent} from '../../../services/admin/transactions.service';
import {statusLabel} from '../../../services/admin/orders.service';
export function TransactionActivity({id,token}:{id:string;token:string}){
 const [revision,setRevision]=useState(0);const key=JSON.stringify([id,token,revision]);
 const [logs,setLogs]=useState<{key:string;items?:TransactionLog[];error?:boolean}>(),[events,setEvents]=useState<{key:string;items?:TransactionEvent[];error?:boolean}>();
 useEffect(()=>{let active=true;transactionsService.timeline(id,token).then(items=>{if(active)setLogs({key,items});}).catch(()=>{if(active)setLogs({key,error:true});});transactionsService.events(id,token).then(items=>{if(active)setEvents({key,items});}).catch(()=>{if(active)setEvents({key,error:true});});return()=>{active=false;};},[id,token,key]);
 const timeline=logs?.key===key?logs:undefined,webhooks=events?.key===key?events:undefined;
 const retry=<button onClick={()=>setRevision(n=>n+1)} className="underline">Retry</button>;
 return <div className="space-y-6 mt-6"><section><h3 className="font-serif text-xl mb-3">Transaction timeline</h3>{!timeline?<p role="status">Loading timeline...</p>:timeline.error?<p role="alert">Unable to load timeline. {retry}</p>:timeline.items?.length?<ol className="space-y-4">{[...timeline.items].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(log=><li key={log.id} className="border-l-2 border-[#E4E4E4] pl-3"><p className="text-sm">{statusLabel(log.type)}{log.status&&' · '+statusLabel(log.status)}</p><time className="text-xs text-[#535353]">{new Date(log.createdAt).toLocaleString('en-CA')}</time>{log.message&&<p className="text-xs mt-1 break-words">{log.message}</p>}</li>)}</ol>:<p className="text-sm">No timeline entries recorded.</p>}</section>
 <section><h3 className="font-serif text-xl mb-3">Stripe events</h3>{!webhooks?<p role="status">Loading events...</p>:webhooks.error?<p role="alert">Unable to load Stripe events. {retry}</p>:webhooks.items?.length?<div className="space-y-4">{[...webhooks.items].sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt)).map(event=><div key={event.id} className="border border-[#E4E4E4] rounded-lg p-4 text-xs"><p className="font-medium break-all">{event.type}</p><p className="mt-2">{event.livemode?'Live mode':'Test mode'} · {statusLabel(event.status)} · {event.attempts} processing attempts</p><p className="mt-1 break-all">{event.id}</p><p className="mt-1">Received: {new Date(event.receivedAt).toLocaleString('en-CA')}</p>{event.processedAt&&<p>Processed: {new Date(event.processedAt).toLocaleString('en-CA')}</p>}{event.errorMessage&&<p className="mt-2 text-neutral-700 break-words">{event.errorMessage}</p>}</div>)}</div>:<p className="text-sm">No Stripe events linked to this transaction.</p>}</section></div>;
}
